spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glass
    username: postgres
    password: xwbk01xn17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  error:
    include-message: always
  port: 8080


